### ISSUE TITLE
onlykey-agent does not work in Parrot OS

### ISSUE THREAD

**Issue by alien2003** [trustcrypto/onlykey-agent#12]
This happens when I try to do something like `onlykey-agent user@192.168.1.1`

```
Traceback (most recent call last):
  File "/home/alien/.local/bin/onlykey-agent", line 10, in <module>
    sys.exit(run_agent())
  File "/home/alien/.local/lib/python2.7/site-packages/onlykey_agent/__main__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/alien/.local/lib/python2.7/site-packages/onlykey_agent/__main__.py", line 140, in run_agent
    public_key = conn.get_public_key(label=label)
  File "/home/alien/.local/lib/python2.7/site-packages/onlykey_agent/client.py", line 85, in get_public_key
    vk = ecdsa.VerifyingKey.from_string(ok_pubkey, curve=ecdsa.NIST256p)
  File "/home/alien/.local/lib/python2.7/site-packages/ecdsa/keys.py", line 46, in from_string
    curve.verifying_key_length, len(string)))
ecdsa.keys.MalformedPointError: Malformed encoding of public point. Expected string 64 bytes long, received 0 bytes long string
```

**Comment by onlykey** [comment]
@alien2003 A new version of onlykey-agent dependency was recently updated. Can you ensure you have v1.1.0 of onlykey?
$ pip2 install onlykey

You can verify with pip freeze and you should have this

onlykey==1.1.0
onlykey-agent==0.0.5

**Comment by alien2003** [comment]
@onlykey that works, thank you

**Comment by alien2003** [comment]
0.0.5 version disappeared from PyPi

**Comment by onlykey** [comment]
@alien2003 0.0.5 was not put on pypi, v1.0.0 is now on pypi
