### ISSUE TITLE
Does Not Work On Solus Linux

### ISSUE THREAD

**Issue by freddyyeddy** [trustcrypto/onlykey-agent#14]
Running:
~$ lsb_release -a
          LSB Version:	1.4
          Distributor ID:	Solus
          Description:	Solus 
          Release:	4.0
          Codename:	fortitude
I got everything to install just fine. But it fails when i try to run
~$ onlykey-agent sam@siteground
           Traceback (most recent call last):
           File "/usr/bin/onlykey-agent", line 10, in <module>
           sys.exit(run_agent())
           File "/usr/lib/python2.7/site-packages/onlykey_agent/__main__.py", line 123, in wrapper
           return func(*args, **kwargs)
           File "/usr/lib/python2.7/site-packages/onlykey_agent/__main__.py", line 140, in 
           run_agent
           public_key = conn.get_public_key(label=label)
           File "/usr/lib/python2.7/site-packages/onlykey_agent/client.py", line 85, in get_public_key
           vk = ecdsa.VerifyingKey.from_string(ok_pubkey, curve=ecdsa.NIST256p)
           File "/usr/lib/python2.7/site-packages/ecdsa/keys.py", line 37, in from_string
    (len(string), curve.verifying_key_length)
           AssertionError: (0, 64)

Hopefully its a simple fix. Thank you for your time and help
On a similar note anyway you guys could add a Solus port for the main app?

**Comment by onlykey** [comment]
@freddyyeddy Are you able to test the latest version - https://docs.crp.to/upgradeguide.html
