### ISSUE TITLE
IOError: open failed

### ISSUE THREAD

**Issue by haplo** [trustcrypto/onlykey-agent#19]
I don't know what happened, but my Onlykey stopped working with `onlykey-agent` only when trying to use git. `onlykey-agent` works when connecting to my servers via SSH (with `-c`), but trying any git operation fails with an IOError:

```
$ onlykey-agent -v -e e haplo@github.com git clone git@github.com:haplo/python-onlykey.git
2020-03-14 00:21:35,823 INFO         getting public key from OnlyKey...                                                                   [client.py:54]
2020-03-14 00:21:35,823 INFO         Trying to read the public key...                                                                     [client.py:55]
2020-03-14 00:21:35,824 INFO         Identity hash ="<cut>" [client.py:67]
2020-03-14 00:21:36,326 INFO         received= '<cut>' [client.py:75]
2020-03-14 00:21:36,326 INFO         Received Public Key generated by OnlyKey= '<cut>' [client.py:79]
2020-03-14 00:21:36,326 INFO         using SSH public key: xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx                                [__main__.py:109]
2020-03-14 00:21:36,329 INFO         running ['git', 'clone', 'git@github.com:haplo/python-onlykey.git', 'onlykey-python'] with {'SSH_AUTH_SOCK': '/tmp/ssh-agent-cJdrmG', 'SSH_AGENT_PID': '6395'} [server.py:140]
Cloning into 'onlykey-python'...
2020-03-14 00:21:37,149 ERROR        failed to connect                                                                                    [client.py:192]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onlykey/client.py", line 184, in _connect
    self._hid.open_path(path)
  File "hid.pyx", line 72, in hid.device.open_path
IOError: open failed
2020-03-14 00:21:38,654 ERROR        failed to connect                                                                                    [client.py:192]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onlykey/client.py", line 184, in _connect
    self._hid.open_path(path)
  File "hid.pyx", line 72, in hid.device.open_path
IOError: open failed
```

`onlykey-agent` worked before, I was able to clone three of my repositories, but now no git command works.

**Comment by haplo** [comment]
Today I tried again and it worked, no idea what fixed it.
