### ISSUE TITLE
How to "Generate your First SSH Key on the OnlyKey Plug"

### ISSUE THREAD

**Issue by jmdesprez** [trustcrypto/onlykey-agent#22]
Hello,

I'm trying to configure my onlykey using: https://docs.crp.to/onlykey-agent.html#ssh-agent-quickstart-guide with no luck.

From step 2 It seems I need to "Generate your First SSH Key on the OnlyKey Plug" but the documentation doesn't indicate how to do that.

BTW if I try to follow the documentation and then run `onlykey-agent identity@myhost` it throws an error message: 
```
Traceback (most recent call last):
  File "/home/user/.local/bin/onlykey-agent", line 8, in <module>
    sys.exit(run_agent())
  File "/home/user/.local/lib/python2.7/site-packages/onlykey_agent/__main__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/onlykey_agent/__main__.py", line 140, in run_agent
    public_key = conn.get_public_key(label=label)
  File "/home/user/.local/lib/python2.7/site-packages/onlykey_agent/client.py", line 68, in get_public_key
    self.ok.send_message(msg=Message.OKGETPUBKEY, slot_id=132, payload=data)
  File "/home/user/.local/lib/python2.7/site-packages/onlykey/client.py", line 252, in send_message
    raw_bytes.extend(bytearray.fromhex(payload))
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

**Comment by jmdesprez** [comment]
Documentation has been updated
