### ISSUE TITLE
KeyError: 'libagent'

### ISSUE THREAD

**Issue by muh2000** [trustcrypto/onlykey-agent#25]
hi guys, i am trying to get things running but i am stuck at this point:
what am i missing?

onlykey-agent -sk 106 -c user@example.com
Traceback (most recent call last):
  File "/usr/local/bin/onlykey-agent", line 33, in <module>
    sys.exit(load_entry_point('onlykey-agent==1.1.10', 'console_scripts', 'onlykey-agent')())
  File "/usr/local/lib/python3.8/dist-packages/onlykey_agent-1.1.10-py3.8.egg/EGG-INFO/scripts/onlykey_agent.py", line 5, in <lambda>
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 256, in main
    args = create_agent_parser(device_type=device_type).parse_args()
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 76, in create_agent_parser
    resources = [resources_map[agent_package], resources_map['libagent']]
KeyError: 'libagent'

**Comment by onlykey** [comment]
@muh2000 Can you verify you installed onlykey-agent following instructions here:
https://docs.crp.to/onlykey-agent.html#installation

If so its possible there is something unique to your setup, can you use a clean VM here to verify that works for you:
https://www.osboxes.org/ubuntu/

**Comment by muh2000** [comment]
@onlykey thank you.
