### ISSUE TITLE
Only Key Agent, unable to generate new keys on fedora

### ISSUE THREAD

**Issue by laincorp** [trustcrypto/onlykey-agent#35]
Python error stack trace :

Traceback (most recent call last):
  File "/home/user/.local/bin/onlykey-agent", line 8, in <module>
    sys.exit(ssh_agent())
  File "/home/user/.local/bin/onlykey_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/user/.local/lib/python3.10/site-packages/libagent/ssh/__init__.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/libagent/ssh/__init__.py", line 323, in main
    for pk in conn.public_keys():
  File "/home/user/.local/lib/python3.10/site-packages/libagent/ssh/__init__.py", line 221, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/user/.local/lib/python3.10/site-packages/libagent/ssh/client.py", line 28, in export_public_keys
    pubkey = formats.export_public_key(vk=vk, label=label)
  File "/home/user/.local/lib/python3.10/site-packages/libagent/formats.py", line 252, in export_public_key
    key_type, blob = serialize_verifying_key(vk)
  File "/home/user/.local/lib/python3.10/site-packages/libagent/formats.py", line 235, in serialize_verifying_key
    if (len(vk) == 279 or len(vk) == 535):
TypeError: object of type 'NoneType' has no len()

I installed the agent by following the instructions at https://docs.crp.to/onlykey-agent.html#installation

**Comment by laincorp** [comment]
Closed
